#!/bin/sh
#
#

temp_success="1"
/bin/rm  -f output.txt outputa.txt 
tname="diamondSurf"

#################################################################
#
#################################################################
CANTERA_DATA=${CANTERA_DATA:=../../data/inputs}; export CANTERA_DATA

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./runDiamond diamond_blessed.xml > output.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="0"
  echo "runDiamond ($tname test) returned with bad status, $retnStat, check output"
  exit 1
fi

../../bin/exp3to2.sh output.txt > outputa.txt
diff -w outputa.txt runDiamond_blessed.out > diff_test.out
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on $tname test"
  exit 0
else
  echo "unsuccessful diff comparison on $tname test"
  echo "FAILED" > csvCode.txt
  temp_success="0"
  exit 1
fi

../../bin/exp3to2.sh diamond.xml > diamonda.xml
diff -w diamonda.xml diamond_blessed.xml > xml_diff_test.out
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on $tname diamond.xml test"
  exit 0
else
  echo "unsuccessful diff comparison on $thame diamond.xml test"
  echo "FAILED" > csvCode.txt
  temp_success="0"
  exit 1
fi


