#!/bin/sh
#
#

temp_success="1"
/bin/rm  -f output.txt outputa.txt 
tname="printUtilUnitTest"

#################################################################
#
#################################################################
CANTERA_DATA=${CANTERA_DATA:=../../data/inputs}; export CANTERA_DATA

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./pUtest > output.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="0"
  echo "$tname ($tname test) returned with bad status, $retnStat, check output"
fi

../../bin/exp3to2.sh output.txt > outputa.txt
diff -w outputa.txt output_blessed.txt > diff_test.out
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on $tname test"
  return 0
else
  echo "unsuccessful diff comparison on $tname test"
  echo "FAILED" > csvCode.txt
  temp_success="0"
  return 1
fi

