
OPTION(CANTERA_BUILD_FULL_PYTHON "Include support for using Cantera from Python?" ON)

OPTION(CANTERA_BUILD_WITH_F2C "Use f2c versions of 3rd party numerical routines" OFF)

OPTION (CANTERA_BUILD_LAPACK  0)
OPTION (CANTERA_HAVE_SUNDIALS 1)

SET( PYTHON_CMD ${PYTHON_EXE})

SET( CANTERA_VERSION "1.7.1")

SET( WITH_PURE_FLUIDS  1 )

SET( WITH_LATTICE_SOLID 1 )

SET( WITH_METAL 1 )

SET( WITH_STOICH_SUBSTANCE 1 )

SET ( WITH_IDEAL_SOLUTIONS 1 )

SET (WITH_ELECTROLYTES 1 )
