name = "Cantera"
uuid = "c8cccd67-5bbd-4b73-b352-8d151246ed36"
authors = ["Cantera Developers <developers@cantera.org>"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
