#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f output_0.txt    diff_csv.txt diff_out_0.txt output.txt output_a.txt

##########################################################################

prog=NASA_coeffs
if test ! -x $prog ; then
   echo $prog ' does not exist'
   exit -1
fi
#################################################################
#
CANTERA_DATA=${CANTERA_DATA:=../../../data/inputs}; export CANTERA_DATA
CANTERA_BIN=${CANTERA_BIN:=../../../bin}

#################################################################

$prog  > output_0.txt <<+
1.0
+
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="0"
  echo "$prog returned with bad status, $retnStat, check output"
fi

${CANTERA_BIN}/exp3to2.sh output_0.txt > output_a.txt
cat output_a.txt | sed /'press any'/d > output.txt


diff -w output_0_blessed.txt output.txt > diff_out_0.txt
retnStat_0=$?


retnTotal=1
if test $retnStat_0 = "0" 
then
  retnTotal=0
fi


if test $retnTotal = "0"
then
  echo "Successful test comparison on "`pwd`
else
  echo "Unsuccessful test comparison on "`pwd` " test"
  echo "         txt files are different - see diff_test*.txt"
fi

