[build-system]
# These versions are updated to the latest versions supported in cibuildwheel
# at the time of this commit. Feel free to update as required.
requires = [
  "setuptools>=67.6.1",
  "wheel",
  "oldest-supported-numpy",
  "Cython>=0.29.34",
]
build-backend = "setuptools.build_meta"
