"""SDist of the Python Module"""
from pathlib import Path
import shutil
import re

Import("env", "build", "install")

localenv = env.Clone()


def copy_ext_src(target, source, env):
    target_ext = Path(target[0].abspath)
    source_ext = Path(source[0].abspath)
    if target_ext.is_dir():
        shutil.rmtree(target_ext)

    # fmt library
    FMT_ROOT = target_ext / "fmt"
    FMT_ROOT.mkdir(parents=True)  # Needed to be able to use copy2
    for cc_file in (source_ext / "fmt" / "src").glob("*.cc"):
        shutil.copy2(cc_file, FMT_ROOT)
    shutil.copytree(source_ext / "fmt" / "include" / "fmt", FMT_ROOT / "fmt")

    # libexecstream
    EXECSTREAM_ROOT = target_ext / "libexecstream"
    EXECSTREAM_ROOT.mkdir(parents=True)  # Needed to be able to use copy2
    shutil.copy2(source_ext / "libexecstream" / "exec-stream.cpp", EXECSTREAM_ROOT)
    shutil.copy2(source_ext / "libexecstream" / "exec-stream.h", EXECSTREAM_ROOT)
    shutil.copytree(source_ext / "libexecstream" / "win", EXECSTREAM_ROOT / "win")
    shutil.copytree(source_ext / "libexecstream" / "posix", EXECSTREAM_ROOT / "posix")

    # yaml-cpp library
    YAML_ROOT = target_ext / "yaml-cpp"
    shutil.copytree(source_ext / "yaml-cpp" / "src", YAML_ROOT)
    shutil.copytree(source_ext / "yaml-cpp" / "include" / "yaml-cpp",
                    YAML_ROOT / "yaml-cpp")

    # SUNDIALS library
    SUNDIALS_ROOT = target_ext / "sundials"
    subdirs = ["sundials", "nvector/serial", "cvodes", "ida", "sunmatrix/band",
               "sunmatrix/dense", "sunmatrix/sparse", "sunlinsol/dense",
               "sunlinsol/band", "sunlinsol/spgmr", "sunnonlinsol/newton"]
    ignores = shutil.ignore_patterns("fsun*", "CMake*", "fmod", "fcmix")
    for subdir in subdirs:
        shutil.copytree(
            source_ext / "sundials" / "src" / subdir,
            SUNDIALS_ROOT / subdir,
            ignore=ignores,
        )


def replace_git_hash(target, source, env):
    # Avoid having to set a C preprocessor define at compile time, since
    # the git commit is unknown from the sdist
    target = Path(target[0].abspath)
    source = Path(source[0].abspath)
    git_commit_replaced = re.sub("#ifdef GIT_COMMIT.*?#endif",
                                 f"""    return "{env['git_commit']}";""",
                                 source.read_text(),
                                 flags=re.DOTALL)
    target.write_text(git_commit_replaced)


# Use RecursiveInstall to be able to exclude files and folders.
build(localenv.RecursiveInstall(
    "src",
    "#src",
    exclude=["fortran", "matlab", r"global\.cpp", "SCons.*"],
))

build(localenv.Command("src/base/global.cpp", "#src/base/global.cpp",
                       replace_git_hash))

include_target = build(localenv.Command("include", "#include",
                                        Copy("$TARGET", "$SOURCE")))
localenv.Depends(include_target, env["config_h_target"])
localenv.Depends(include_target, env["ext_include_copies_target"])

build(localenv.Command("ext", "#ext", copy_ext_src))

# Use RecursiveInstall to make sure that files are not overwritten during the copy.
# A normal Copy Action would fail because of the existing directories.
build(localenv.RecursiveInstall("#interfaces/python_sdist/cantera",
                                "#interfaces/cython/cantera",
                                exclude=["__pycache__"]))
build(localenv.RecursiveInstall("#interfaces/python_sdist/cantera/data",
                                "#data", exclude=[r"\.xml", r"\.cti"]))
build(localenv.RecursiveInstall("#interfaces/python_sdist/cantera/test/data",
                                "#test/data"))

# Copy the minimal Sundials configuration template into the sdist so that
# it can be filled in at compile time on the user's machine
build(localenv.Command("sundials_config.h.in", "#ext/sundials_config.h.in",
                       Copy("$TARGET", "$SOURCE")))

build(localenv.SubstFile("setup.cfg", "setup.cfg.in"))
license = build(localenv.Command("LICENSE.txt", "#build/ext/LICENSE.txt",
                                 Copy("$TARGET", "$SOURCE")))
localenv.Depends(license, localenv["license_target"])
