#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f output.txt outputa.txt
testName="baseopt_red1"

#################################################################
#
#################################################################
CANTERA_DATA=${CANTERA_DATA:=../../data/inputs}; export CANTERA_DATA

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./basopt_red1 > output.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="0"
  echo "$testName returned with bad status, $retnStat, check output"
  exit 1
fi

diff -w output.txt output_blessed.txt > diff_test.out
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on $testName test"
  exit 0
else
  echo "unsuccessful diff comparison on $testName test"
  echo "FAILED" > csvCode.txt
  temp_success="0"
  exit 1
fi

