#!/bin/sh
###############################################################
#  $Author: hkmoffa $
#  $Date: 2010-03-19 18:26:02 -0600 (Fri, 19 Mar 2010) $
#  $Revision: 420 $
###############################################################
#

all: 
	cd StoichSolidKinetics;         gmake all

depends:
	cd StoichSolidKinetics ;         gmake depends

clean:
	cd StoichSolidKinetics ;         gmake clean

test:
	cd StoichSolidKinetics ;         gmake -s test

rebaseline:
	cd StoichSolidKinetics ;         gmake rebaseline



