#!/bin/sh


PY_DEMOS = critProperties rankine

all:
	@(for py in $(PY_DEMOS) ; do \
	  (cd $${py} ; make ) \
	done)

run:
	@(for py in $(PY_DEMOS) ; do \
	    echo "running $${py}..."; \
	  (cd $${py} ; make run ) \
	done)

test:
	@(for py in $(PY_DEMOS) ; do \
	    echo "testing $${py}..."; \
	  (cd $${py} ; make test) \
	done)


clean:
	@(for py in $(PY_DEMOS) ; do \
	    echo "cleaning $${py}..."; \
	  (cd $${py} ; make clean) \
	done)



# end of file

