from buildutils import *

Import('env', 'build', 'install')
localenv = env.Clone()

programs = [('cti2ctml', ['cti2ctml.cpp']),
            ('ck2cti', ['ck2cti.cpp'])]

localenv.Append(CPPPATH=['#src', '#include'])

for name, src in programs:
    prog = build(localenv.Program(target=pjoin('#build/bin', name),
                                  source=src,
                                  LIBS=['cantera']))
    install('$inst_bindir', prog)

# Copy man pages
if env['INSTALL_MANPAGES']:
    install('$inst_mandir', mglob(localenv, 'man', '*'))
