.TH "mixmaster" 1 "16 Nov 2003" "mixmaster" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mixmaster \- graphical tool for analysis of chemically-reacting mixtures.  

.SH SYNOPSIS
.br
mixmaster

.SH DESCRIPTION

.I mixmaster
is a graphical application written in Python that can be used to postprocess 
simulations carried out with Cantera, or to explore the properties of mixtures 
and reaction mechanisms. 


