latsol.o: latsol.cpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/Cantera.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/ct_defs.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/config.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_Version.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_ConfigDefs.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_config.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_MathFunctions.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_Fad_ExpressionTraits.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_Traits.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_Fad_DFadTraits.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_ScalarFlopCounterTraits.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_Fad_DFad.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_Fad_GeneralFadExpr.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_Fad_GeneralFad.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_Fad_Expression.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_dummy_arg.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_Fad_GeneralFadImp.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_Fad_Ops.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_cmath.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_Fad_DynamicStorage.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_DynamicArrayTraits.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/sacadoLite/Sacado_ScalarFlopCounter.hpp \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/global.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/ct_defs.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/ctexceptions.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/logger.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/clockWC.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/xml.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/ctexceptions.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/global.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/stringUtils.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/Array.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/utilities.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/vec_functions.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/ThermoFactory.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/ThermoPhase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/Phase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/vec_functions.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/ctml.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/xml.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/Array.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/Elements.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/ct_defs.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/SpeciesThermo.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/xml.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/ct_thread.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/FactoryBase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/SurfPhase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/mix_defs.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/EdgePhase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/SurfPhase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/GibbsExcessVPSSTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/VPStandardStateTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/VPSSMgr.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/MargulesVPSSTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/GibbsExcessVPSSTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/electrolyteThermo.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/electrolytes.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/MolalityVPSSTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/VPStandardStateTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/IdealMolalSoln.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/MolalityVPSSTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/WaterPropsIAPWS.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/WaterPropsIAPWSphi.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/config.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/WaterProps.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/PDSS.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/PDSS_Water.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/PDSS.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/PDSS_HKFT.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/HMWSoln.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/electrolytes.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/DebyeHuckel.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/Array.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/WaterSSTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/SingleSpeciesTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/VPSSMgr_Water_HKFT.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/VPSSMgr_Water_ConstVol.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/LatticePhase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/utilities.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/LatticeSolidPhase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/LatticePhase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/kernel/MargulesVPSSTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/kernel/FixedChemPotSSTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/kernel/mix_defs.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/kernel/SingleSpeciesTP.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/kernel/SpeciesThermo.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/kernel/LatticeSolidPhase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/equilibrium.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/equil/equil.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/equil/MultiPhase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/numerics/DenseMatrix.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/thermo/ThermoPhase.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/equil/vcs_defs.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/equil/ChemEquil.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/ctexceptions.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/equil/MultiPhaseEquil.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/equil/MultiPhaseEquil.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/equil/vcs_MultiPhaseEquil.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/kernel/vcs_internal.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/equil/vcs_defs.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/base/global.h \
 /home/hkmoffa/arch/linux64_gcc444/canteraJacobians_dbg/include/cantera/kernel/logger.h
