#!/bin/sh
#
#
temp_success="1"

##########################################################################
prog=latsol
if test ! -x $prog ; then
   echo $prog ' does not exist'
   exit -1
fi
##########################################################################
/bin/rm  -f output.txt 
/bin/rm -f test.out test.diff   output.txt diff_test.out
/bin/rm -f CheckDebug.txt output_bc.txt

#################################################################
#
CANTERA_DATA=${CANTERA_DATA:=../../../data/inputs}; export CANTERA_DATA
CANTERA_BIN=${CANTERA_BIN:=../../../bin}

#################################################################

$prog  > output.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="0"
  echo "$prog returned with bad status, $retnStat, check output"
fi


diff -w output_blessed.txt output.txt > diff_test.out
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on `pwd` test"
else
  echo "unsuccessful diff comparison on `pwd` test"
  echo "FAILED" > csvCode.txt
  temp_success="0"
fi

