from buildutils import *

Import('env', 'buildTargets', 'installTargets')

localenv = env.Clone()

build = localenv.Command('#build/docs/html/index.html',
                         'doxygen/Doxyfile', 'doxygen $SOURCE')
buildTargets.extend(build)

if localenv['addInstallTargets']:
    inst = localenv.Install(pjoin('$inst_docdir', 'html'),
                            mglob(localenv, '#/build/docs/html',
                                  'html', 'svg', 'css', 'png'))
    installTargets.extend(inst)
