
disp('building Cantera...');
mex -I../../../build/include private/ctmethods.cpp ...
    private/ctfunctions.cpp ...
    private/xmlmethods.cpp private/phasemethods.cpp  ...
    private/thermomethods.cpp private/kineticsmethods.cpp ...
    private/transportmethods.cpp private/reactormethods.cpp ...
    private/wallmethods.cpp private/flowdevicemethods.cpp ...
    private/onedimmethods.cpp private/surfmethods.cpp private/write.cpp ...
    ../../../lib/clib.lib ../../../lib/oneD.lib ...
    ../../../lib/zeroD.lib ../../../lib/transport.lib ...
    ../../../lib/cantera.lib ../../../lib/recipes.lib ...
    ../../../lib/cvode.lib ../../../lib/ctlapack.lib ...
    ../../../lib/ctmath.lib ../../../lib/ctblas.lib ...
    ../../../lib/tpx.lib ...
    ../../../lib/dformd.lib ../../../lib/dfconsol.lib ...
    ../../../lib/dfport.lib
disp('done.');
