
#ifndef CKR_CONFIG_H
#define CKR_CONFIG_H

namespace ckr {

/**
 *  define to enable parsing Chemkin-III plasma reactions. Not yet fully 
 *  implemented, so best to leave it undefined for now.
 */ 	
#undef ENABLE_PLASMA_REACTIONS

}


/**
 * @file config.h
 * Header file generated by configure script. To change options,
 * edit config.h.in and re-run configure.
 * @author David G. Goodwin, Caltech
 */
 
#endif


