.TH "ctml2yaml" 1 "6 Feb 2021" "ctml2yaml" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctml2yaml \- convert legacy CTML-format mechanisms to Cantera YAML input files

.SH SYNOPSIS
\fBctml2yaml\fR \fIinput\fR [\fIoutput\fR] [-h | --help]

.SH DESCRIPTION

The parameters are as follows:
.TP
.I input
The CTML (XML) file to be converted.
.TP
[\fIoutput\fR]
The name of the output file. By default, an output file will be
created with the same name as the input file, with the extension
changed to \fB.yaml\fR.
.TP
.B -h | --help
Show a help message and exit.

.SH EXAMPLE
ctml2yaml mymech.xml
