#!/bin/sh
#
#

temp_success="1"
/bin/rm  -f output.txt

#################################################################
#
#################################################################
CANTERA_DATA=${CANTERA_DATA:=../../data/inputs}; export CANTERA_DATA

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./surfdemo > output.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="0"
  echo "surfdemo returned with bad status, $retnStat, check output"
fi

diff -w output.txt output_blessed.txt > diff_test.out
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on surfkin test"
  return 0
else
  echo "unsuccessful diff comparison on surfkin test"
  echo "FAILED" > csvCode.txt
  temp_success="0"
  return 1
fi

