/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__cantera___cantera
#define __PYX_HAVE__cantera___cantera


#ifndef __PYX_HAVE_API__cantera___cantera

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *pyCanteraError;

#endif /* !__PYX_HAVE_API__cantera___cantera */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_cantera(void);
#else
PyMODINIT_FUNC PyInit__cantera(void);
#endif

#endif /* !__PYX_HAVE__cantera___cantera */
