avogadro: float
boltzmann: float
electron_charge: float
electron_mass: float
epsilon_0: float
faraday: float
gas_constant: float
light_speed: float
one_atm: float
permeability_0: float
planck: float
stefan_boltzmann: float
