from typing import Literal

from cantera.thermo import PureFluid

def Water(backend: Literal["Reynolds", "IAPWS95"] = "Reynolds") -> PureFluid: ...
def Nitrogen() -> PureFluid: ...
def Methane() -> PureFluid: ...
def Hydrogen() -> PureFluid: ...
def Oxygen() -> PureFluid: ...
def Hfc134a() -> PureFluid: ...
def CarbonDioxide() -> PureFluid: ...
def Heptane() -> PureFluid: ...
