#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f output.txt outputa.txt
testName="ChemEquil_ionizedGas"

#################################################################
#
#################################################################
CANTERA_DATA=${CANTERA_DATA:=../../data/inputs}; export CANTERA_DATA

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./ionizedGasEquil > output.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="1"
  echo "ERROR: $testName: ionizedGasEquil returned with bad status, $retnStat, check output"
fi

diff -w output.txt output_blessed.txt > diff_test.out
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on $testName test"
  temp_success="0"
else
  echo "FAILED: unsuccessful diff comparison on $testName test"
  echo "FAILED" > csvCode.txt
fi

