
disp('building Cantera...');
diary
mex -v -I../../../build/include private/ctmethods.cpp ...
    private/ctfunctions.cpp ...
    private/xmlmethods.cpp private/phasemethods.cpp  ...
    private/thermomethods.cpp private/kineticsmethods.cpp ...
    private/mixturemethods.cpp ...
    private/transportmethods.cpp private/reactormethods.cpp ...
    private/reactornetmethods.cpp ...
    private/wallmethods.cpp private/flowdevicemethods.cpp ...
    private/funcmethods.cpp ...
    private/onedimmethods.cpp private/surfmethods.cpp ...
    ../../../build/lib/i686-pc-win32/clib.lib
disp('done.');
diary off
exit;
%    ../../../build/lib/i686-pc-win32/oneD.lib ...
%    ../../../build/lib/i686-pc-win32/zeroD.lib ...
%    ../../../build/lib/i686-pc-win32/transport.lib ...
%    ../../../build/lib/i686-pc-win32/cantera.lib ...
%    ../../../build/lib/i686-pc-win32/recipes.lib ...
%    ../../../build/lib/i686-pc-win32/cvode.lib ...
%    ../../../build/lib/i686-pc-win32/ctlapack.lib ...
%    ../../../build/lib/i686-pc-win32/ctmath.lib ...
%    ../../../build/lib/i686-pc-win32/ctblas.lib ...
%    ../../../build/lib/i686-pc-win32/tpx.lib 
