#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f output.txt outputa.txt 
tname="mixGasTransport"
#################################################################
#
#################################################################
CANTERA_DATA=${CANTERA_DATA:=../../data/inputs}; export CANTERA_DATA

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./statmech_test > output.txt

exit $?
