#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f output2.txt  diff_test2.txt
tname="surfaceSolver2"
#
#################################################################
#
#################################################################
CANTERA_DATA=${CANTERA_DATA:=../../data/inputs}; export CANTERA_DATA

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./surfaceSolver2 -d 3 haca2.xml > output2.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="0"
  echo "surfaceSolver ($tname test) returned with bad status, $retnStat, check output"
fi

diff -w output2.txt surfaceSolver2_blessed3.out > diff_test2.txt
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on $tname d3 test"
else
  echo "unsuccessful diff comparison on $tname d3 test"
  echo "FAILED" > csvCode.txt
  temp_success="0"
fi


