from buildutils import *

Import('env', 'buildTargets', 'installTargets')

localenv = env.Clone()

lib = localenv.Library(target=pjoin('..','..','lib','fct'),
                       source=mglob(localenv, 'src', 'f90', 'cpp'))
inst = localenv.Install('$ct_libdir', lib)

# Copy the mod files to the include directory
for mod in mglob(localenv, 'src', 'mod'):
    copy = localenv.Command('../../include/cantera/%s' % mod.name, mod,
                            Copy('$TARGET', '$SOURCE'))
    localenv.AddPostAction(lib, copy)
