function ctGenerateLibraryDefinitions(includeDir, headerDir, ctLibDir, outputDir)
    % Generate paths for header files
    headerFiles = dir(fullfile(headerDir, '**', '*.h'));
    headerPaths = string({headerFiles.name});
    headerPaths = fullfile({headerFiles.folder}, headerPaths);

    % Get path for the shared library file
    libraries = ctLib(ctLibDir);

    overwriteExistingDefinitionFiles = true;

    % Set up C++ compiler
    mex -setup cpp

    % Generate definition file for C++ library
    clibgen.generateLibraryDefinition(headerPaths, ...
        "IncludePath",includeDir, ...
        "Libraries",libraries, ...
        "OutputFolder",outputDir, ...
        "InterfaceName","ctMatlab", ...
        "OverwriteExistingDefinitionFiles",overwriteExistingDefinitionFiles, ...
        "CLinkage",true, ...
        "TreatObjectPointerAsScalar",true, ...
        "TreatConstCharPointerAsCString",true, ...
        "ReturnCArrays",false, ...
        "Verbose",true);
end
