from buildutils import *

Import('env', 'buildTargets', 'installTargets')

localenv = env.Clone()
lib = localenv.Library(pjoin('../../lib', 'ctcxx'),
                       source=mglob(localenv, 'src', 'cpp'))
inst = localenv.Install('$ct_libdir', lib)

buildTargets.extend(lib)
installTargets.extend(inst)
