#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f output_0.txt  equil_koh.csv  diff_csv.txt diff_out_0.txt

##########################################################################
prog=multiphase_plasma.py
if test ! -f $prog ; then
   echo $prog ' does not exist'
   exit -1
fi
#################################################################
#
CANTERA_DATA=${CANTERA_DATA:=../../../data/inputs}; export CANTERA_DATA
CANTERA_BIN=${CANTERA_BIN:=../../../bin}

#################################################################

$PYTHON_CMD $prog  > output_0.txt <<+
1.0
+
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="0"
  echo "$prog returned with bad status, $retnStat, check output"
fi

diff -w output_blessed_0.txt output_0.txt > diff_out_0.txt
retnStat_0=$?

csvdiff -a 1.0E-15 equil_koh_blessed_0.csv equil_koh.csv  > diff_csv.txt
retnStat_csv_0=$?

retnTotal=1
if test $retnStat_0 = "0" 
then
  retnTotal=0
fi

retnCSVTotal=1
if test $retnStat_csv_0 = "1" 
then
  retnCSVTotal=0
fi

if test $retnCSVTotal = "0"
then
  echo "Successful test comparison on "`pwd`
    if test $retnTotal = "1"
    then
       echo "  But text files show differences see diff_out_0.txt"
    fi
else
  echo "Unsuccessful test comparison on "`pwd` " test"
  if test $retnTotal != "0"
  then
     echo "      files are different - see diff_test*.txt"
  fi
fi

