#!/bin/sh
#
#

temp_success="1"
/bin/rm  -f eq1.csv  tr1.csv tr2.csv  kin1.csv  kin2.csv

#################################################################
#
#################################################################

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./silane_equil > output.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="0"
  echo "silane_equil returned with bad status, $retnStat, check output"
fi


diff output.txt output_blessed.txt > diff_test.out
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on silane_equil test"
else
  echo "unsuccessful diff comparison on silane_equil test"
  echo "FAILED" > csvCode.txt
  temp_success="0"
fi

