#!/bin/sh
#
#
CANTERA_INSTALL_DIR=/home/hkmoffa/arch/linux64_gcc424/cantera-1.8_liquidTransportDevelop
export CANTERA_INSTALL_DIR
#
CANTERA_ROOT=/home/hkmoffa/Cantera/gc/canteraLiquidTransportDevelop
export CANTERA_ROOT
#
CADS_ROOT=/home/hkmoffa/Cantera/cads_linux64_gcc424
export CADS_ROOT
#
PYTHON_DIR=/home/hkmoffa/arch/linux64_gcc424/python-2.6.4
export PYTHON_DIR
#
#  BUILD_WITH_F2C is optional on linux. 
#
export BUILD_WITH_F2C='n'
#
#
#CANTERA_CONFIG_PREFIX=/home/hkmoffa/arch/linux
#export CANTERA_CONFIG_PREFIX
#
SET_PYTHON_SITE_PACKAGE_TOPDIR=y
export SET_PYTHON_SITE_PACKAGE_TOPDIR
#
PYTHON_SITE_PACKAGE_TOPDIR=/home/hkmoffa/arch/linux64_gcc424/python-2.6.4
export PYTHON_SITE_PACKAGE_TOPDIR
#
CXX=/sierra/Sntools/extras/compilers/gcc-4.2.4/bin/g++
export CXX

#
CXXFLAGS="-g -Wall -DDEBUG_HKM"
export CXXFLAGS
#
LCXX_END_LIBS=" -lgfortran"
export LCXX_END_LIBS
#
# Specify the fortran compiler, because some libraries are
# written in fortran. This is used to find the libraries
# to link against
#
F77='/sierra/Sntools/extras/compilers/gcc-4.2.4/bin/gfortran'
export F77
FFLAGS="-g -DDEBUG_HKM  -fno-second-underscore"
export FFLAGS

export MPIHOME=/sierra/Sntools/extras/mpi/mpich-1.2.7p1-gcc-4.2.4-64Bit

MPICXX=/sierra/Sntools/extras/mpi/mpich-1.2.7p1-gcc-4.2.4-64Bit/bin/mpiCC
export MPICXX

MPICC=/sierra/Sntools/extras/mpi/mpich-1.2.7p1-gcc-4.2.4-64Bit/bin/mpicc
export MPICC

MPIF77=/sierra/Sntools/extras/mpi/mpich-1.2.7p1-gcc-4.2.4-64Bit/bin/mpif77
export MPIF77

CXX_DEPENDS='/sierra/Sntools/extras/mpi/mpich-1.2.7p1-gcc-4.2.4-64Bit/bin/mpiCC -MM'
export CXX_DEPENDS 

export DO_MPI='y'


#
MAKE=gmake
export MAKE
#
./preconfig
