
disp('building Cantera as a statically linked mex application ...');
mex -v  -Ic:/vc_env/cant17/build/include private/ctmethods.cpp private/ctfunctions.cpp ...
    private/xmlmethods.cpp private/phasemethods.cpp  ...
    private/thermomethods.cpp private/kineticsmethods.cpp ...
    private/transportmethods.cpp private/reactormethods.cpp ...
    private/reactornetmethods.cpp ...
    private/wallmethods.cpp private/flowdevicemethods.cpp ...
    private/funcmethods.cpp ...
    private/mixturemethods.cpp ...
    private/onedimmethods.cpp private/surfmethods.cpp  ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/clibstatic.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/oneD.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/zeroD.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/transport.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/equil.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/kinetics.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/thermo.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/numerics.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/converters.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/base.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/ctcxx.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/tpx.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/NVEC_SER.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/CVODES.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/SUNDIALS_SHARED.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/ctmath.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/ctlapack.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/ctblas.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/ctf2c.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/ctlapack.lib ...
    c:/vc_env/cant17/build/lib/i686-pc-win32/ctblas.lib ...
   
