function Load_Cantera
    addpath('Class', 'Utility', 'PresetObjects', 'Examples');
    if ~libisloaded('cantera_shared')
        load('Utility/cantera_root.mat');
        [~,warnings] = loadlibrary([cantera_root '/lib/cantera_shared.dll'], ...
                                          [cantera_root '/include/cantera/clib/ctmatlab.h'], ...
                                          'includepath', [cantera_root '/include'], ...
                                          'addheader','ct','addheader','ctfunc', ...
                                          'addheader','ctmultiphase','addheader', ...
                                          'ctonedim','addheader','ctreactor', ...
                                          'addheader','ctrpath','addheader','ctsurf', ...
                                          'addheader','ctxml');
    end
    disp('Cantera is ready for use');
end
